port: 3000
db:
    mongodb:
        -   enabled: true
            host: localhost
            port: 27017
            database: demo
            nameconn: connMongo
            lang: ES

relationdb:
    mongodb:
        -   enabled: true
            host: localhost
            port: 27017
            database: demo
            nameconn: connMongo
            lang: ES   
jwtkey: AEuIoPJKMN2323_qewe=qe